name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build, Tag and Push docker image to DockerHub
      env:
        REGISTERY: ${{ secrets.DOCKER_USERNAME }}
        REPOSITORY: albumrestapi
        IMAGE_TAG: latest
      run: |
        docker build -t $REGISTERY/$REPOSITORY:$IMAGE_TAG ./.
        docker push $REGISTERY/$REPOSITORY:$IMAGE_TAG
